name: Main Workflow

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

jobs:
  calculate-sp-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate SP and add comment
        uses: ./.github/workflows/calculate-sp.yml
